# Generated by Django 2.2.7 on 2019-11-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipebox', '0003_auto_20191125_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorite',
        ),
        migrations.AddField(
            model_name='author',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='recipebox.Recipe'),
        ),
    ]
